[workspace]
members = ["server", "client", "signal", "phonex"]
resolver = "2"

[workspace.dependencies]
webrtc = "0.12.0"
tracing_spanned = { git = "https://github.com/comnipl/tracing_spanned", rev = "6fed6097d13d117e4d35120f56450b156c33b77e" }
